const JobData = [
    {
        field: "Tech",
        img: "technova.png",
        role: "Frontend Developer",
        company: "TechNova",
        where: "Remote",
        salary: "$70k - $90k/year",
        tags: ["JavaScript", "React", "HTML/CSS", "UI Development"],
        description: "Develop responsive user interfaces using React.js and modern CSS. Collaborate with design team to implement pixel-perfect UIs.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 2 days ago"
    },
    {
        field: "Tech",
        img: "codecraft.png",
        role: "Backend Engineer",
        company: "CodeCraft",
        where: "Austin, TX",
        salary: "$85k - $110k/year",
        tags: ["Node.js", "Python", "API Development", "Database"],
        description: "Design and optimize backend services and database architecture. Implement RESTful APIs for our SaaS platform.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Tech",
        img: "technova.png",
        role: "DevOps Engineer",
        company: "TechNova",
        where: "Seattle, WA",
        salary: "$95k - $120k/year",
        tags: ["AWS", "Docker", "CI/CD", "Infrastructure"],
        description: "Automate deployment pipelines and maintain cloud infrastructure. Implement monitoring and alerting systems.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 5 days ago"
    },
    {
        field: "Tech",
        img: "innova.png",
        role: "Cybersecurity Analyst",
        company: "InnovaWorks",
        where: "Remote",
        salary: "$90k - $115k/year",
        tags: ["Security", "Networking", "Risk Assessment", "Compliance"],
        description: "Conduct security audits and vulnerability assessments. Implement security policies and incident response plans.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 3 days ago"
    },
    {
        field: "Tech",
        img: "codecraft.png",
        role: "QA Engineer",
        company: "CodeCraft",
        where: "Denver, CO",
        salary: "$70k - $95k/year",
        tags: ["Testing", "Automation", "Selenium", "Quality Assurance"],
        description: "Develop test plans and automate regression tests. Work with developers to reproduce and resolve bugs.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Tech",
        img: "codecraft.png",
        role: "Full Stack Developer",
        company: "CodeCraft",
        where: "San Diego, CA",
        salary: "$100k - $125k/year",
        tags: ["JavaScript", "React", "Node.js", "Fullstack"],
        description: "Build end-to-end features for our web application. Work across the stack from database to UI components.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 4 days ago"
    },
    {
        field: "Tech",
        img: "technova.png",
        role: "Mobile App Developer",
        company: "TechNova",
        where: "Remote",
        salary: "$80k - $100k/year",
        tags: ["React Native", "iOS", "Android", "Mobile"],
        description: "Develop cross-platform mobile apps using React Native. Implement native modules when needed.",
        experience: "Mid-level",
        employmentType: "Contract",
        posted: "Posted 6 days ago"
    },
    {
        field: "Tech",
        img: "innova.png",
        role: "Cloud Architect",
        company: "InnovaWorks",
        where: "New York, NY",
        salary: "$110k - $140k/year",
        tags: ["AWS", "Azure", "Cloud", "Infrastructure"],
        description: "Design scalable cloud infrastructure solutions. Lead migration of on-prem systems to cloud.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 2 weeks ago"
    },
    {
        field: "Tech",
        img: "codecraft.png",
        role: "Machine Learning Engineer",
        company: "CodeCraft",
        where: "Remote",
        salary: "$115k - $145k/year",
        tags: ["Python", "TensorFlow", "AI", "Data Science"],
        description: "Develop and deploy machine learning models. Optimize model performance for production.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 3 days ago"
    },
    {
        field: "Tech",
        img: "technova.png",
        role: "Site Reliability Engineer",
        company: "TechNova",
        where: "Chicago, IL",
        salary: "$105k - $135k/year",
        tags: ["DevOps", "Monitoring", "Scalability", "SRE"],
        description: "Ensure high availability of production systems. Automate operational workflows.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Design",
        img: "designly.png",
        role: "UI/UX Designer",
        company: "Designly",
        where: "New York, NY",
        salary: "$60k - $80k/year",
        tags: ["Figma", "User Research", "Wireframing", "Prototyping"],
        description: "Create user flows and high-fidelity prototypes. Conduct usability testing sessions.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 5 days ago"
    },
    {
        field: "Design",
        img: "designly.png",
        role: "Content Strategist",
        company: "Designly",
        where: "Remote",
        salary: "$50k - $68k/year",
        tags: ["Content", "SEO", "Copywriting", "Strategy"],
        description: "Develop content strategy and editorial calendar. Optimize content for search and engagement.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 2 days ago"
    },
    {
        field: "Design",
        img: "designly.png",
        role: "Graphic Designer",
        company: "Designly",
        where: "Austin, TX",
        salary: "$55k - $70k/year",
        tags: ["Adobe Creative Suite", "Illustration", "Branding", "Print"],
        description: "Create marketing materials and brand assets. Work on both digital and print designs.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Design",
        img: "designly.png",
        role: "Creative Director",
        company: "Designly",
        where: "Los Angeles, CA",
        salary: "$90k - $120k/year",
        tags: ["Leadership", "Art Direction", "Branding", "Strategy"],
        description: "Lead creative vision for all brand projects. Manage team of designers and copywriters.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 3 weeks ago"
    },
    {
        field: "Design",
        img: "designly.png",
        role: "Visual Designer",
        company: "Designly",
        where: "Remote",
        salary: "$65k - $85k/year",
        tags: ["UI Design", "Illustration", "Branding", "Digital"],
        description: "Create visual assets for digital products. Maintain design system consistency.",
        experience: "Mid-level",
        employmentType: "Contract",
        posted: "Posted 4 days ago"
    },
    {
        field: "Design",
        img: "designly.png",
        role: "Product Designer",
        company: "Designly",
        where: "Chicago, IL",
        salary: "$75k - $95k/year",
        tags: ["UX", "Prototyping", "User Research", "Figma"],
        description: "Design user experiences for our product suite. Conduct user interviews and testing.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Design",
        img: "designly.png",
        role: "Brand Designer",
        company: "Designly",
        where: "Remote",
        salary: "$58k - $78k/year",
        tags: ["Logo Design", "Brand Identity", "Typography", "Packaging"],
        description: "Develop brand identities for client projects. Create style guides and design systems.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 5 days ago"
    },
    {
        field: "Design",
        img: "designly.png",
        role: "Motion Designer",
        company: "Designly",
        where: "Miami, FL",
        salary: "$65k - $82k/year",
        tags: ["After Effects", "Animation", "Motion Graphics", "Video"],
        description: "Create animated assets for digital products and marketing. Design micro-interactions.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 2 days ago"
    },
    {
        field: "Design",
        img: "designly.png",
        role: "Interaction Designer",
        company: "Designly",
        where: "Boston, MA",
        salary: "$70k - $90k/year",
        tags: ["UX", "Prototyping", "User Flows", "Microinteractions"],
        description: "Design intuitive user flows and interactions. Create detailed prototypes.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Design",
        img: "designly.png",
        role: "Design Researcher",
        company: "Designly",
        where: "Remote",
        salary: "$60k - $88k/year",
        tags: ["User Research", "Usability Testing", "Qualitative", "Interviews"],
        description: "Plan and conduct user research studies. Synthesize findings into actionable insights.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 3 days ago"
    },
    {
        field: "Data",
        img: "insightful.png",
        role: "Data Analyst",
        company: "Insightful",
        where: "Chicago, IL",
        salary: "$65k - $85k/year",
        tags: ["SQL", "Excel", "Visualization", "Reporting"],
        description: "Analyze business data and create reports. Build dashboards for stakeholders.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Data",
        img: "insightful.png",
        role: "Market Research Associate",
        company: "Insightful",
        where: "Boston, MA",
        salary: "$60k - $78k/year",
        tags: ["Research", "Surveys", "Competitive Analysis", "Trends"],
        description: "Conduct market research and competitive analysis. Prepare research reports.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 5 days ago"
    },
    {
        field: "Data",
        img: "insightful.png",
        role: "Data Scientist",
        company: "Insightful",
        where: "Remote",
        salary: "$90k - $115k/year",
        tags: ["Python", "Machine Learning", "Statistics", "Pandas"],
        description: "Develop predictive models and analyze complex datasets. Communicate findings to stakeholders.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 2 days ago"
    },
    {
        field: "Data",
        img: "insightful.png",
        role: "Business Intelligence Analyst",
        company: "Insightful",
        where: "San Francisco, CA",
        salary: "$85k - $105k/year",
        tags: ["Power BI", "Tableau", "SQL", "Dashboards"],
        description: "Develop BI dashboards and reports. Analyze business performance metrics.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Data",
        img: "insightful.png",
        role: "Quantitative Analyst",
        company: "Insightful",
        where: "New York, NY",
        salary: "$100k - $130k/year",
        tags: ["Statistics", "Modeling", "Finance", "R"],
        description: "Develop statistical models for financial analysis. Backtest trading strategies.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 3 weeks ago"
    },
    {
        field: "Data",
        img: "insightful.png",
        role: "Data Engineer",
        company: "Insightful",
        where: "Seattle, WA",
        salary: "$95k - $120k/year",
        tags: ["ETL", "Big Data", "Spark", "Data Pipelines"],
        description: "Build and maintain data pipelines. Optimize data warehouse performance.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 4 days ago"
    },
    {
        field: "Data",
        img: "insightful.png",
        role: "Research Data Coordinator",
        company: "Insightful",
        where: "Remote",
        salary: "$60k - $78k/year",
        tags: ["Data Collection", "Cleaning", "Organization", "Research"],
        description: "Clean and organize research datasets. Ensure data quality standards.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Data",
        img: "insightful.png",
        role: "Data Governance Analyst",
        company: "Insightful",
        where: "Denver, CO",
        salary: "$70k - $90k/year",
        tags: ["Compliance", "Security", "Metadata", "Quality"],
        description: "Implement data governance policies. Maintain data dictionary and lineage.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 5 days ago"
    },
    {
        field: "Data",
        img: "insightful.png",
        role: "Statistical Modeler",
        company: "Insightful",
        where: "Atlanta, GA",
        salary: "$85k - $110k/year",
        tags: ["Statistics", "R", "Predictive Modeling", "Regression"],
        description: "Develop statistical models for business forecasting. Validate model accuracy.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 2 weeks ago"
    },
    {
        field: "Data",
        img: "insightful.png",
        role: "ETL Developer",
        company: "Insightful",
        where: "Phoenix, AZ",
        salary: "$80k - $100k/year",
        tags: ["ETL", "SQL", "Data Warehousing", "Integration"],
        description: "Design and implement ETL processes. Optimize data transformation jobs.",
        experience: "Mid-level",
        employmentType: "Contract",
        posted: "Posted 3 days ago"
    },
    {
        field: "Business",
        img: "innova.png",
        role: "Product Manager",
        company: "InnovaWorks",
        where: "San Francisco, CA",
        salary: "$100k - $130k/year",
        tags: ["Agile", "Roadmapping", "User Stories", "Prioritization"],
        description: "Lead product development from conception to launch. Define product roadmap and strategy.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Business",
        img: "innova.png",
        role: "Sales Executive",
        company: "InnovaWorks",
        where: "Atlanta, GA",
        salary: "$65k + commission",
        tags: ["B2B", "CRM", "Negotiation", "Account Management"],
        description: "Generate new business opportunities. Manage key client accounts and relationships.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 4 days ago"
    },
    {
        field: "Business",
        img: "innova.png",
        role: "Operations Manager",
        company: "InnovaWorks",
        where: "Dallas, TX",
        salary: "$90k - $115k/year",
        tags: ["Process Improvement", "Logistics", "Efficiency", "Leadership"],
        description: "Oversee daily operations and implement process improvements. Manage operational team.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 2 weeks ago"
    },
    {
        field: "Business",
        img: "innova.png",
        role: "Business Analyst",
        company: "InnovaWorks",
        where: "Chicago, IL",
        salary: "$75k - $95k/year",
        tags: ["Requirements", "Process Mapping", "Stakeholder Management", "Analysis"],
        description: "Analyze business processes and recommend improvements. Document business requirements.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 5 days ago"
    },
    {
        field: "Business",
        img: "innova.png",
        role: "Partnership Manager",
        company: "InnovaWorks",
        where: "Remote",
        salary: "$85k - $110k/year",
        tags: ["Relationship Management", "Negotiation", "Business Development", "Networking"],
        description: "Develop and manage strategic partnerships. Identify new partnership opportunities.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 3 days ago"
    },
    {
        field: "Business",
        img: "innova.png",
        role: "Strategic Planner",
        company: "InnovaWorks",
        where: "Boston, MA",
        salary: "$95k - $120k/year",
        tags: ["Market Analysis", "Competitive Intelligence", "Strategy", "Planning"],
        description: "Develop long-term business strategies. Conduct market and competitive analysis.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Business",
        img: "innova.png",
        role: "Account Manager",
        company: "InnovaWorks",
        where: "Remote",
        salary: "$60k - $85k/year",
        tags: ["Client Relations", "Retention", "Upselling", "CRM"],
        description: "Manage portfolio of client accounts. Identify upsell and cross-sell opportunities.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 2 days ago"
    },
    {
        field: "Business",
        img: "innova.png",
        role: "Operations Analyst",
        company: "InnovaWorks",
        where: "Seattle, WA",
        salary: "$70k - $90k/year",
        tags: ["Data Analysis", "Process Improvement", "Reporting", "Optimization"],
        description: "Analyze operational data to identify improvement opportunities. Create performance reports.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Business",
        img: "innova.png",
        role: "Business Development Associate",
        company: "InnovaWorks",
        where: "New York, NY",
        salary: "$65k - $88k/year",
        tags: ["Prospecting", "Lead Generation", "Pitching", "Market Research"],
        description: "Identify and qualify new business opportunities. Assist with sales presentations.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 4 days ago"
    },
    {
        field: "Business",
        img: "innova.png",
        role: "Growth Manager",
        company: "InnovaWorks",
        where: "Remote",
        salary: "$90k - $125k/year",
        tags: ["Marketing", "Experimentation", "Metrics", "Scaling"],
        description: "Develop and execute growth strategies. Analyze metrics to optimize performance.",
        experience: "Senior",
        employmentType: "Full-time",
        posted: "Posted 2 weeks ago"
    },
    {
        field: "Marketing",
        img: "designly.png",
        role: "Digital Marketing Specialist",
        company: "Designly",
        where: "Los Angeles, CA",
        salary: "$55k - $75k/year",
        tags: ["SEO", "PPC", "Social Media", "Content"],
        description: "Execute digital marketing campaigns across multiple channels. Analyze campaign performance.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 5 days ago"
    },
    {
        field: "Marketing",
        img: "designly.png",
        role: "Content Marketing Manager",
        company: "Designly",
        where: "Remote",
        salary: "$70k - $90k/year",
        tags: ["Blogging", "SEO", "Editorial Calendar", "Storytelling"],
        description: "Develop content strategy and manage content production. Optimize content for SEO.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Marketing",
        img: "designly.png",
        role: "SEO Specialist",
        company: "Designly",
        where: "New York, NY",
        salary: "$60k - $78k/year",
        tags: ["Keyword Research", "On-page SEO", "Analytics", "Link Building"],
        description: "Optimize website content and structure for search engines. Conduct keyword research.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 3 days ago"
    },
    {
        field: "Marketing",
        img: "designly.png",
        role: "Social Media Manager",
        company: "Designly",
        where: "Remote",
        salary: "$58k - $75k/year",
        tags: ["Content Creation", "Community Management", "Analytics", "Brand Voice"],
        description: "Manage social media accounts and engagement. Develop social content calendar.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 2 days ago"
    },
    {
        field: "Marketing",
        img: "designly.png",
        role: "Email Marketing Coordinator",
        company: "Designly",
        where: "Boston, MA",
        salary: "$55k - $70k/year",
        tags: ["Email Campaigns", "Automation", "A/B Testing", "CRM"],
        description: "Design and execute email marketing campaigns. Analyze email performance metrics.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Marketing",
        img: "designly.png",
        role: "Marketing Analyst",
        company: "Designly",
        where: "Denver, CO",
        salary: "$60k - $82k/year",
        tags: ["Data Analysis", "ROI", "Campaign Tracking", "Google Analytics"],
        description: "Analyze marketing campaign performance. Provide data-driven recommendations.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 4 days ago"
    },
    {
        field: "Marketing",
        img: "designly.png",
        role: "Brand Marketing Associate",
        company: "Designly",
        where: "Chicago, IL",
        salary: "$65k - $85k/year",
        tags: ["Brand Strategy", "Positioning", "Messaging", "Awareness"],
        description: "Support brand marketing initiatives. Assist with campaign development and execution.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 3 days ago"
    },
    {
        field: "Marketing",
        img: "designly.png",
        role: "PPC Campaign Manager",
        company: "Designly",
        where: "Remote",
        salary: "$70k - $95k/year",
        tags: ["Google Ads", "Facebook Ads", "Retargeting", "Conversion"],
        description: "Manage paid advertising campaigns. Optimize ad spend and targeting.",
        experience: "Mid-level",
        employmentType: "Full-time",
        posted: "Posted 1 week ago"
    },
    {
        field: "Marketing",
        img: "designly.png",
        role: "Marketing Copywriter",
        company: "Designly",
        where: "Seattle, WA",
        salary: "$50k - $68k/year",
        tags: ["Content Creation", "SEO", "Brand Voice", "Persuasive Writing"],
        description: "Write compelling marketing copy for various channels. Maintain brand voice consistency.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 5 days ago"
    },
    {
        field: "Marketing",
        img: "designly.png",
        role: "Influencer Marketing Coordinator",
        company: "Designly",
        where: "San Francisco, CA",
        salary: "$60k - $80k/year",
        tags: ["Influencer Outreach", "Partnerships", "Campaign Management", "Social Media"],
        description: "Identify and manage influencer partnerships. Coordinate influencer marketing campaigns.",
        experience: "Entry-level",
        employmentType: "Full-time",
        posted: "Posted 2 days ago"
    }
];

export default JobData;